### ISSUE TITLE
project_tools.sh adds permissions at the wrong lines

### ISSUE THREAD

**Issue by ghenry** [cloudwebrtc/dart-sip-ua#3]
Running this in example/scripts puts the permissions after the application xml tag in `android/app/src/main/AndroidManifest.xml` causing a failed build.

**Comment by cloudwebrtc** [comment]
I also found this problem in the flutter master channel because of the add-line.py in example/scripts/project_tools.sh uses the wrong line number.
We need a smarter script to modify AndroidManifest.xml and build.gradle from the command line.
Before that, I tried to edit these files with sed, but since sed was inconsistent on mac and Linux, I wrote the ugly script add-line.py.

**Comment by ghenry** [comment]
We can look at something.

**Comment by cloudwebrtc** [comment]
fixed https://github.com/cloudwebrtc/dart-sip-ua/commit/9eaa7fad96f67ee0c088798beca4b4e77fea0f48
